#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Ryan Ming"
email = "hello@ryanming.com"

[ui]
default-command = ["status"]
pager = ["delta", "--pager", "less -FRX"] # Keeps output from terminal after closing the pager
diff-formatter = ":git"
diff-editor = "meld"
merge-editor = "meld"

[[--scope]]
--when.commands = ["diff", "show"] # allow `jj diff` and `jj show` to clear the output from the terminal after closing the pager

[--scope.ui]
pager = "delta"
diff-formatter = ":git"
